### ISSUE TITLE
Segfault when trying to run GQOL query against empty set

### ISSUE THREAD

**Issue by osmuser63783** [clarisma/geodesk-py#50]
Trying to check if a traffic sign is part of a way with a `highway` tag or not:

```
traffic_signs = planet_240219("n[traffic_sign]")
traffic_signs[0].parents.ways("*[highway]")
Segmentation fault (core dumped)
```

(When reading [this](https://community.openstreetmap.org/t/large-scale-change-of-traffic-sign-to-traffic-sign-id/107508/117) I thought challenge accepted, that's easy with Geodesk!)

**Comment by clarisma** [comment]
Thanks! I haven't been able to reproduce this, can you check if you have the latest releases?

- This looks similar to #46 (Affected empty sets in general; fixed in v0.1.7)
- Alternatively, it may be caused by #clarisma/gol-tool#105, which in some cases produced faulty encodings, which in turn caused access to nodes to fail (Fixed in GOL Tool 0.1.9)

**Comment by osmuser63783** [comment]
OK this is odd. I was on Geodesk 0.1.7 and gol-tool 0.1.9. Now I've updated to 0.1.8 and 0.1.10 and re-built my GOL and I can no longer reproduce the issue. Nevermind, sorry about the false positive

**Comment by clarisma** [comment]
Thanks for checking this again. This may still be the sign of a latent bug. Does #51 still fail? (The weird part is that the crash occurred when accessing a *relation*, clarisma/gol-tool#105 only affected ways, but not relations)
